on:
  push:
    tags: ['v[0-9].[0-9]+.[0-9]+']

name: Create Release Assets

jobs:
  buildAndRelease:
    name: Create Release
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Check or Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          architecture: 'x64'

      - name: Install Dependencies
        run: npm i

      - name: Publish The Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish
